### ISSUE TITLE
Knowing about babel-eslint

### ISSUE THREAD

**Issue by sdc224** [electron-react-boilerplate/eslint-config-erb#106] opened 2020-06-28 13:47 UTC
Hi @amilajack , can you tell me why you are using babel-eslint as dependency?

**Comment by sdc224** [comment] 2020-06-28 14:05
For Typescript we can omit it and use only `@typescript-eslint/parser` right?

**Comment by amilajack** [comment] 2020-06-28 16:31
Yes, this library should be removed from our dependencies. Would you be interested in PR'ing the fix?

**Comment by sdc224** [comment] 2020-06-28 16:38
Yes sure, I will do it

**Comment by sdc224** [comment] 2020-06-28 16:54
We can remove `eslint-plugin-compat` also, cause we may not need to worry about polyfills in erb

Also we need to add typescript parsers in dev and peer dependencies. For typescript, we can omit flowtype as well.

I think better is to create a different repo to manage dependencies for `typescript` only, it will reduce peer dep warnings in erb😃

Tell me what should be better, I can make a PR for adding typescript dependencies as well, and also removing `eslint-plugin-compat`

**Comment by sdc224** [comment] 2020-06-28 17:00
@amilajack getting some errors while doing `yarn test`.

Maybe internally `babel-eslint` is used, so we need to move it to dev dependencies.

```ps1 
FAIL  test/basic.spec.js (7.907 s)
  basic
    × should report semicolon errors (4666 ms)

  ● basic › should report semicolon errors

    Failed to load parser 'babel-eslint' declared in 'package.json » ./index.js': Cannot find module 'babel-eslint' from 'index.js'
    Require stack:
    - D:\Programming\Nodejs\ForkWorks\eslint-config-erb\index.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:308:11)
      at Object.resolve (node_modules/eslint/lib/shared/relative-module-resolver.js:28:50)
      at ConfigArrayFactory._loadParser (node_modules/eslint/lib/cli-engine/config-array-factory.js:904:45)
      at ConfigArrayFactory._normalizeObjectConfigDataBody (node_modules/eslint/lib/cli-engine/config-array-factory.js:706:43)
          at _normalizeObjectConfigDataBody.next (<anonymous>)
      at ConfigArrayFactory._normalizeObjectConfigData (node_modules/eslint/lib/cli-engine/config-array-factory.js:647:20)
          at _normalizeObjectConfigData.next (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        10.157 s
```

**Comment by amilajack** [comment] 2020-06-28 17:01
> cause we may not need to worry about polyfills in erb

Why do you think we don't need to worry about polyfills?

**Comment by sdc224** [comment] 2020-06-28 17:03
I have mentioned that in the issue in ERB, let me add it here

**Comment by sdc224** [comment] 2020-06-28 17:05
Please see [this](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2490#issuecomment-650677002)

Also [this](https://www.electronjs.org/docs/tutorial/performance#5-unnecessary-polyfills), as per Electron, we really don't need polyfills. which can improve performance

**Comment by amilajack** [comment] 2020-06-28 17:06
The docs mean that you don't need to polyfill APIs that already exist. Its not saying you don't need to polyfill at all. If an API is not supported in electron/node then `eslint-plugin-compat` will catch that.

**Comment by sdc224** [comment] 2020-06-28 17:07
> The docs mean that you don't need to polyfill APIs that already exist. Its not saying you don't need to polyfill at all. If an API is not supported in electron/node then `eslint-plugin-compat` will catch that.

Ok got your point.

**Comment by amilajack** [comment] 2020-06-28 17:13
`index.js` is for JS users of ERB while `typescript.js` is for TS users that consume this config. ERB currently defaults to the `typescript.js` config. I think we can move all the dependencies used for the javascript config to `optionalDependencies`. I think the best solution is to create a monorepo that contains two eslint configs: one for ts, on for js.

**Comment by sdc224** [comment] 2020-06-28 17:18
Yes best actually, creating a monorepo

**Comment by sdc224** [comment] 2020-06-28 17:21
> The docs mean that you don't need to polyfill APIs that already exist. Its not saying you don't need to polyfill at all. If an API is not supported in electron/node then `eslint-plugin-compat` will catch that.

Can you tell me an example where eslint plugin will catch? I was roaming through internet but couldn't find any

**Comment by amilajack** [comment] 2020-06-28 18:23
Read more about [the project here](https://github.com/amilajack/eslint-plugin-compat).

**Comment by sdc224** [comment] 2020-06-29 15:14
Thanks! I think we should start working on the monorepo

**Comment by amilajack** [comment] 2020-08-20 01:59
Duplicate of https://github.com/electron-react-boilerplate/eslint-config-erb/issues/117

**Closed as completed** 2020-08-20 01:59 UTC
